name: Update Profile README

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  push:
    branches:
      - main  # Change this if your default branch is named differently

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1.2
      with:
        token: ${{ secrets.USER_TOKEN }}
        includeForks: true
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add README.md
          git commit -m "Automatically update README with latest stats"
          git push
        fi
