name: Update Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 30 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Update README
      run: |
        # Example: Simulate fetching data and updating the README
        sed -i "s/{{ ACCOUNT_AGE }}/12/g" README.md
        sed -i "s/{{ COMMITS }}/1500/g" README.md
        sed -i "s/{{ ISSUES }}/45/g" README.md
        sed -i "s/{{ PULL_REQUESTS }}/30/g" README.md
        sed -i "s/{{ STARS }}/78/g" README.md
        sed -i "s/{{ REPOSITORIES }}/20/g" README.md
        sed -i "s/{{ REPOSITORIES_CONTRIBUTED_TO }}/5/g" README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git commit -am "Update README.md" || echo "No changes to commit"
        git push
