name: Update Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 30 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Update README
      run: |
        # Example command to replace placeholders
        sed -i "s/{{ COMMITS }}/$(gh api repos/ascender1729/ascender1729 --jq '.pushed_at')/g" README.md
        # Add similar commands for other placeholders

    - name: Commit and Push if changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Updated README with the latest stats"
          git push
