name: Update Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 5 minutes, the minimum interval

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README
      run: python update_readme.py
    - name: Commit and Push if changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to the output on this push."
        else
          git commit -m "Update README with latest stats"
          git push
        fi
