name: Update Profile README

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Updated to the latest version
    - name: Update README.md
      run: |
        # Add your script or command here to update README.md
        # Example: echo "Update your README here" > README.md
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add README.md
        git commit -m "Automatically update README with latest stats"
        git push
