name: Update Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 5 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Dynamic README
        uses: peerlist/peerlist-profile-action@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Specify any additional options here
      
      - name: Update README
        run: |
          # Your custom commands to update README.md if necessary
          echo "README updated on $(date)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Automatically update README" || echo "No changes to commit"
          git push
