name: Update Profile README

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@latest  # Make sure to check the correct version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          includeForks: true
          readme: ./README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Update README.md" || echo "No changes to commit"
          git push
